### ISSUE TITLE
自定义物品教程出错

### ISSUE THREAD

**Issue by byemypast** [Superice666/BlocklyNukkit#11]
- API类型: blockitem.addShapedCraft
- API目标: 希望实现将配方与物品绑定

- BN解释器版本: 1.2.9.0
- nukkit核心：Nukkit git-9280804 版本 "" (API 1.0.11)
- bug描述：在使用教程中的python——自定义物品一节时出现错误，经过判断是下面加粗这行的问题
以下是全部helloworld.py源码：

#pragma python
logger.info(u"-----Script Start-----")
blockRIS = blockitem.buildItem(990, 0, 1)
blockRIS.setCustomName(u"HelloWorld")
blockitem.setItemLore(blockRIS, u"中文描述测试;第二行;The third")

manager.putEasy("G", blockitem.buildItemFromBlock(blockitem.buildBlock(17, 0)))
**blockitem.addShapedCraft(("G  ", "G  ", "G  "), blockRIS,[])**

- bug提示错误：
03:05:26 [INFO ] [helloworld] -----Script Start-----
03:05:26 [ERROR] [BlocklyNukkit] 无法加载： helloworld.py
org.python.core.PyException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Unknown item mapping Item Unknown (990:0)x1 tags:0x0A00000A0700646973706C61790904004C6F726508030000002400C3A4C2B8C2ADC3A6C296C287C3A6C28FC28FC3A8C2BFC2B0C3A6C2B5C28BC3A8C2AFC2951200C3A7C2ACC2ACC3A4C2BAC28CC3A8C2A1C28C09005468652074686972640804004E616D650A0048656C6C6F576F726C640000
        at org.python.core.Py.JavaError(Py.java:547) ~[PyBN.jar:2.7.2]
        at org.python.core.Py.JavaError(Py.java:538) ~[PyBN.jar:2.7.2]
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:192) ~[PyBN.jar:2.7.2]
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208) ~[PyBN.jar:2.7.2]
        at org.python.core.PyObject.__call__(PyObject.java:512) ~[PyBN.jar:2.7.2]
        at org.python.core.PyObject.__call__(PyObject.java:517) ~[PyBN.jar:2.7.2]
        at org.python.core.PyMethod.__call__(PyMethod.java:171) ~[PyBN.jar:2.7.2]
        at org.python.pycode._pyx1.f$0(<string>:8) ~[?:?]
        at org.python.pycode._pyx1.call_function(<string>) ~[?:?]
        at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[PyBN.jar:2.7.2]
        at org.python.core.PyCode.call(PyCode.java:18) ~[PyBN.jar:2.7.2]
        at org.python.core.Py.runCode(Py.java:1687) ~[PyBN.jar:2.7.2]
        at org.python.core.Py.exec(Py.java:1731) ~[PyBN.jar:2.7.2]
        at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:277) ~[PyBN.jar:2.7.2]
        at com.blocklynukkit.loader.scriptloader.PythonLoader.putPythonEngine(PythonLoader.java:89) ~[BlocklyNukkit.jar:1.7.25]
        at com.blocklynukkit.loader.scriptloader.PythonLoader.loadplugins(PythonLoader.java:46) [BlocklyNukkit.jar:1.7.25]
        at com.blocklynukkit.loader.Loader.onEnable(Loader.java:251) [BlocklyNukkit.jar:1.7.25]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:743) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:732) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:575) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.IllegalArgumentException: Unknown item mapping Item Unknown (990:0)x1 tags:0x0A00000A0700646973706C61790904004C6F726508030000002400C3A4C2B8C2ADC3A6C296C287C3A6C28FC28FC3A8C2BFC2B0C3A6C2B5C28BC3A8C2AFC2951200C3A7C2ACC2ACC3A4C2BAC28CC3A8C2A1C28C09005468652074686972640804004E616D650A0048656C6C6F576F726C640000
        at cn.nukkit.item.RuntimeItemMapping.getNetworkFullId(RuntimeItemMapping.java:26) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.utils.BinaryStream.putSlot(BinaryStream.java:471) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.protocol.CraftingDataPacket.encode(CraftingDataPacket.java:102) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.network.protocol.DataPacket.tryEncode(DataPacket.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.inventory.CraftingManager.rebuildPacket(CraftingManager.java:210) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at com.blocklynukkit.loader.script.BlockItemManager.addShapedCraft(BlockItemManager.java:303) ~[BlocklyNukkit.jar:1.7.25]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190) ~[PyBN.jar:2.7.2]
        ... 21 more

**Comment by SuperIceCN** [comment]
根据您给出的报错信息，问题的根源是您使用了不存在的物品id`990`，并将其存入变量`blockRIS`中后，在所加粗代码中使用了无效的物品对象`blockRIS (id=990)`导致的，请仔细核对[基岩版物品id表](https://wiki.biligame.com/mc/%E5%9F%BA%E5%B2%A9%E7%89%88%E6%95%B0%E6%8D%AE%E5%80%BC)，确认id无误后重试插件，感谢您的支持

**Comment by byemypast** [comment]
首先特别感谢开发者，这个插件真的特别棒（要是java版也有类似的就好了2333）

我（最初）的理解是，我认为“自定义物品”（即buildItem）是指创建一个新的Item，这个Item指从0开始，需要制定Item的ID、材质、名称、合成配方、交互……所以才会buildItem一个id 990为了避免“冲突”。

而根据您的回复，我猜测buildItem实现的功能是实例化一个已存在的物品类型，并在这个物品类型上进行addShapedCraft、setCustomName……所以如果需要实现我的功能，需要首先从物品ID表中找到类似的物品ID，然后再进行其他的操作

非常感谢，按理说这个脚本层面的问题可能不应该发issue……感谢能在百忙之中抽空回复

**Comment by SuperIceCN** [comment]
不客气，欢迎提出这样的问题。  
`builditem`的确是根据给出的信息将已经存在的物品实例化，如果您想要使用原版不存在的物品，需要先使用注册函数注册您的物品，并绑定发送给客户端渲染的材质包。  
或许[BNWIKI](https://wiki.blocklynukkit.com/)对您会有帮助。  

再次感谢您对BlocklyNukkit项目的支持，如果没有问题的话，您可以关闭此issue，感谢！

**Comment by byemypast** [comment]
谢谢！没问题啦，给作者拜个早年~！
